<?php

namespace Trans\Commands;

use Illuminate\Console\Command;
use Illuminate\Support\Facades\File;
use Trans\Support\TranslationKeyExtractor;

class TransScanCommand extends Command
{
    protected $signature = 'trans:scan
                            {--dry-run : Only show what would be done without updating the file}
                            {--module= : Scan only the specified module and store in its lang/en.json}
                            {--exclude=* : Paths to exclude when scanning}
                            {--i18n= : Path to export Quasar/JS-friendly translation file (converting :placeholder to {placeholder})}';

    protected $description = 'Scan codebase for translation keys and update en.json';

    public function handle(TranslationKeyExtractor $extractor): int
    {
        $module = $this->option('module');

        if ($module) {
            $this->info("Scanning module [{$module}] for translation keys...");
        } else {
            $this->info('Scanning codebase for translation keys...');
        }

        $extraExcludes = $this->parseExcludeOption();
        $keys = $extractor->scan($module, $extraExcludes);

        $this->info('Found '.count($keys).' unique translation keys.');

        $this->updateTranslationFile($keys, $module);

        return self::SUCCESS;
    }

    protected function updateTranslationFile(array $keys, ?string $module = null): void
    {
        $langPath = $module
            ? base_path("modules/{$module}/resources/lang")
            : base_path('resources/lang');

        $enPath = $langPath.'/en.json';

        if (! File::exists($langPath)) {
            File::makeDirectory($langPath, 0755, true);
        }

        $existingTranslations = [];
        if (File::exists($enPath)) {
            $existingTranslations = json_decode(File::get($enPath), true) ?? [];
        }

        $newTranslations = [];
        $addedCount = 0;

        foreach ($keys as $key) {
            if (! array_key_exists($key, $existingTranslations)) {
                $newTranslations[$key] = $key;
                $addedCount++;
            } else {
                $newTranslations[$key] = $existingTranslations[$key];
            }
        }

        foreach ($existingTranslations as $key => $value) {
            if (! in_array($key, $keys)) {
                $newTranslations[$key] = $value;
            }
        }

        ksort($newTranslations);

        if ($this->option('dry-run')) {
            $target = $module ? "modules/{$module}/lang/en.json" : 'resources/lang/en.json';
            $this->info("Dry run: {$addedCount} keys would be added to {$target}.");

            if ($this->option('i18n')) {
                $this->info("Dry run: Would export JS translations to {$this->option('i18n')}.");
            }

            return;
        }

        File::put($enPath, json_encode($newTranslations, JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE));

        $target = $module ? "modules/{$module}/lang/en.json" : 'resources/lang/en.json';
        $this->info("Success! Successfully updated {$target}. Added {$addedCount} new keys.");

        if ($i18nFile = $this->option('i18n')) {
            $this->exportI18nFile($newTranslations, $i18nFile);
        }
    }

    protected function exportI18nFile(array $translations, string $i18nFile): void
    {
        $i18nTranslations = [];
        foreach ($translations as $key => $value) {
            $i18nKey = preg_replace('/:([a-zA-Z_][a-zA-Z0-9_]*)/', '{$1}', $key);
            $i18nValue = preg_replace('/:([a-zA-Z_][a-zA-Z0-9_]*)/', '{$1}', $value);
            $i18nTranslations[$i18nKey] = $i18nValue;
        }
        ksort($i18nTranslations);

        $jsonContent = json_encode($i18nTranslations, JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE);
        $jsContent = "// English, en-US\n// This file was auto-generated by laravel-trans\n\nexport default ".$jsonContent.";\n";

        $i18nPath = base_path($i18nFile);
        $i18nDirectory = dirname($i18nPath);
        if (! File::exists($i18nDirectory)) {
            File::makeDirectory($i18nDirectory, 0755, true);
        }

        File::put($i18nPath, $jsContent);
        $this->info("Success! Exported Quasar/JS translation file to {$i18nFile}.");
    }

    /**
     * @return string[]
     */
    protected function parseExcludeOption(): array
    {
        $excludeOption = $this->option('exclude') ?: [];
        $paths = [];
        foreach ($excludeOption as $value) {
            if (str_contains($value, ',')) {
                $paths = array_merge($paths, array_map('trim', explode(',', $value)));
            } else {
                $paths[] = trim($value);
            }
        }

        return $paths;
    }
}
